### PR TITLE
Builder:  add Semigroup instance (GHC 8.4 compat)

### LINKED ISSUE #2: SMP-induced failure on 8.4.1
```
    [1 of 1] Compiling Data.String.Builder ( src/Data/String/Builder.hs, dist/build/Data/String/Builder.o )

    src/Data/String/Builder.hs:44:10: error:
        • No instance for (Semigroup Builder)
            arising from the superclasses of an instance declaration
        • In the instance declaration for ‘Monoid Builder’
       |
    44 | instance Monoid Builder where
       |          ^^^^^^^^^^^^^^
    builder for ‘/nix/store/idknvpwa8q6mrdm69p6pj3ck1mxk535m-stringbuilder-0.5.0.drv’ failed with exit code 1
```

### PR DESCRIPTION
**Pull request by deepfire**
Tested on GHC 7.10.3, 8.0.2 and 8.4.1-alpha1.

Fixes #2

### CODE REVIEW

**Comment by deepfire** [comment]
CI failure looks unrelated..

**Comment by sol** [comment]
@deepfire thanks a lot for looking into this!

One issue with this approach is that it's not `-Werror`-sane.  For this reason and for simplicity I prefer a more lightweight approach along the lines of https://github.com/hspec/nanospec/commit/658b55878ffd03a114bf60cdb42692db72a34fd7 (only adding a `Semigroup` instance for `base-4.11.0.*` and later).

**Comment by deepfire** [comment]
@sol, done!  Tested on the aforementioned three compilers once more.

**Comment by sol** [comment]
LGTM!

Thanks a lot!

**Pull request merged**
